CREATE TABLE tb_users (
 id VARCHAR(255) PRIMARY KEY,
 login VARCHAR(255) NOT NULL UNIQUE,
 name VARCHAR(150) NOT NULL,
 password VARCHAR(255),
 email VARCHAR(150) NOT NULL UNIQUE,
 gender VARCHAR(6) NOT NULL,
 cellphone VARCHAR(16) UNIQUE,
 enabled BOOLEAN NOT NULL,
 role VARCHAR(13) NOT NULL,
 city VARCHAR(255) NOT NULL,
 state VARCHAR(255) NOT NULL,
 country VARCHAR(255) NOT NULL
);
